#!/usr/bin/env bash

################################################################################
#
# Predefined ANSI color codes for colorful output strings.
#
# WARNING: This is not an executable script. This script is meant to be used as
# a utility by sourcing this script for efficient bash script writing.
#
################################################################################
# Author : Mark Lucernas <https://github.com/marklcrns>
# Date   : 2020-08-13
################################################################################


if [ "${0##*/}" == "${BASH_SOURCE[0]##*/}" ]; then
  echo "WARNING: $(realpath -s $0) is not meant to be executed directly!" >&2;
  echo "Use this script only by sourcing it." >&2;
  exit 1
fi

# Header guard
[[ -z "${COMMON_COLORS_SH_INCLUDED+x}" ]] \
  && readonly COMMON_COLORS_SH_INCLUDED=1 \
  || return 0


COLOR_ANSI_CODE_PREFIX='\033'

# Regular Colors
COLOR_BLACK="${CODE_ANSI_CODE_PREFIX}[0;30m"
COLOR_RED="${CODE_ANSI_CODE_PREFIX}[0;31m"
COLOR_GREEN="${CODE_ANSI_CODE_PREFIX}[0;32m"
COLOR_YELLOW="${CODE_ANSI_CODE_PREFIX}[0;33m"
COLOR_BLUE="${CODE_ANSI_CODE_PREFIX}[0;34m"
COLOR_PURPLE="${CODE_ANSI_CODE_PREFIX}[0;35m"
COLOR_CYAN="${CODE_ANSI_CODE_PREFIX}[0;36m"
COLOR_WHITE="${CODE_ANSI_CODE_PREFIX}[0;37m"

# Bold
COLOR_BO_BLACK="${CODE_ANSI_CODE_PREFIX}[1;30m"
COLOR_BO_RED="${CODE_ANSI_CODE_PREFIX}[1;31m"
COLOR_BO_GREEN="${CODE_ANSI_CODE_PREFIX}[1;32m"
COLOR_BO_YELLOW="${CODE_ANSI_CODE_PREFIX}[1;33m"
COLOR_BO_BLUE="${CODE_ANSI_CODE_PREFIX}[1;34m"
COLOR_BO_PURPLE="${CODE_ANSI_CODE_PREFIX}[1;35m"
COLOR_BO_CYAN="${CODE_ANSI_CODE_PREFIX}[1;36m"
COLOR_BO_WHITE="${CODE_ANSI_CODE_PREFIX}[1;37m"
COLOR_BO_NC="${CODE_ANSI_CODE_PREFIX}[1m"

# Underline
COLOR_UL_BLACK="${CODE_ANSI_CODE_PREFIX}[4;30m"
COLOR_UL_RED="${CODE_ANSI_CODE_PREFIX}[4;31m"
COLOR_UL_GREEN="${CODE_ANSI_CODE_PREFIX}[4;32m"
COLOR_UL_YELLOW="${CODE_ANSI_CODE_PREFIX}[4;33m"
COLOR_UL_BLUE="${CODE_ANSI_CODE_PREFIX}[4;34m"
COLOR_UL_PURPLE="${CODE_ANSI_CODE_PREFIX}[4;35m"
COLOR_UL_CYAN="${CODE_ANSI_CODE_PREFIX}[4;36m"
COLOR_UL_WHITE="${CODE_ANSI_CODE_PREFIX}[4;37m"
COLOR_UL_NC="${CODE_ANSI_CODE_PREFIX}[4m"

# Background
COLOR_BG_BLACK="${CODE_ANSI_CODE_PREFIX}[40m"
COLOR_BG_RED="${CODE_ANSI_CODE_PREFIX}[41m"
COLOR_BG_GREEN="${CODE_ANSI_CODE_PREFIX}[42m"
COLOR_BG_YELLOW="${CODE_ANSI_CODE_PREFIX}[43m"
COLOR_BG_BLUE="${CODE_ANSI_CODE_PREFIX}[44m"
COLOR_BG_PURPLE="${CODE_ANSI_CODE_PREFIX}[45m"
COLOR_BG_CYAN="${CODE_ANSI_CODE_PREFIX}[46m"
COLOR_BG_WHITE="${CODE_ANSI_CODE_PREFIX}[47m"
COLOR_BG_EXPAND="${CODE_ANSI_CODE_PREFIX}[K"

# High Intensty
COLOR_HI_BLACK="${CODE_ANSI_CODE_PREFIX}[0;90m"
COLOR_HI_RED="${CODE_ANSI_CODE_PREFIX}[0;91m"
COLOR_HI_GREEN="${CODE_ANSI_CODE_PREFIX}[0;92m"
COLOR_HI_YELLOW="${CODE_ANSI_CODE_PREFIX}[0;93m"
COLOR_HI_BLUE="${CODE_ANSI_CODE_PREFIX}[0;94m"
COLOR_HI_PURPLE="${CODE_ANSI_CODE_PREFIX}[0;95m"
COLOR_HI_CYAN="${CODE_ANSI_CODE_PREFIX}[0;96m"
COLOR_HI_WHITE="${CODE_ANSI_CODE_PREFIX}[0;97m"

# Bold High Intensty
COLOR_BO_HI_BLACK="${CODE_ANSI_CODE_PREFIX}[1;90m"
COLOR_BO_HI_RED="${CODE_ANSI_CODE_PREFIX}[1;91m"
COLOR_BO_HI_GREEN="${CODE_ANSI_CODE_PREFIX}[1;92m"
COLOR_BO_HI_YELLOW="${CODE_ANSI_CODE_PREFIX}[1;93m"
COLOR_BO_HI_BLUE="${CODE_ANSI_CODE_PREFIX}[1;94m"
COLOR_BO_HI_PURPLE="${CODE_ANSI_CODE_PREFIX}[1;95m"
COLOR_BO_HI_CYAN="${CODE_ANSI_CODE_PREFIX}[1;96m"
COLOR_BO_HI_WHITE="${CODE_ANSI_CODE_PREFIX}[1;97m"

# High Intensty backgrounds
COLOR_BG_HI_BLACK="${CODE_ANSI_CODE_PREFIX}[0;100m"
COLOR_BG_HI_RED="${CODE_ANSI_CODE_PREFIX}[0;101m"
COLOR_BG_HI_GREEN="${CODE_ANSI_CODE_PREFIX}[0;102m"
COLOR_BG_HI_YELLOW="${CODE_ANSI_CODE_PREFIX}[0;103m"
COLOR_BG_HI_BLUE="${CODE_ANSI_CODE_PREFIX}[0;104m"
COLOR_BG_HI_PURPLE="${CODE_ANSI_CODE_PREFIX}[0;105m"
COLOR_BG_HI_CYAN="${CODE_ANSI_CODE_PREFIX}[0;106m"
COLOR_BG_HI_WHITE="${CODE_ANSI_CODE_PREFIX}[0;107m"

# Reset to Default
COLOR_NC="${CODE_ANSI_CODE_PREFIX}[0m"

